server:
  port: 8088
  tomcat:
    max-swallow-size: 500MB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bishe
    username: root
    password: 7410
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.sports.entity # 这里放置你的实体类包名
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名自动转换



  salt: geelysdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      resolve-lazily: true

